### ISSUE TITLE
Could not find de.idnow.sdk:idnow-android-3.21.0:.

### ISSUE THREAD

**Issue by nitishlovesandroid** [bitwala/react-native-idnow#12]
Could not find de.idnow.sdk:idnow-android-3.21.0:.

**Comment by NazarYablonskiy** [comment]
Thank you @nitishlovesandroid for reporting!
Could you try the newest version and provide more info if the issue is still there?

**Comment by NazarYablonskiy** [comment]
Must be fixed now.
@nitishlovesandroid feel free to re-open.
