### ISSUE TITLE
Android : Error: environment when calling startVideoIdent

### ISSUE THREAD

**Issue by pawel-piatkowski-meelogic** [bitwala/react-native-idnow#3]
Hello @NazarYablonskiy,
Thanks for your great work on this project. It works perfectly for me on iOS. However I can't get it to work on Android. When I call
```
try {
   await IDnowManager.startVideoIdent({
      transactionToken: kycID
   });
} catch (e) {
   logger.log("IDnow exception: ", e)
}
```

I get a runtime error:
```
IDnow exception:  Error: environment
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at e (RNDebuggerWorker.js:1)
```

I'm using react-native-idnow version 0.0.4

any help will be greatly appreciated

**Comment by pradel** [comment]
Hey, can you try with the version `0.0.5`? This issue should be fixed.

**Comment by pawel-piatkowski-meelogic** [comment]
It works with 0.0.5. Thanks for such a quick reaction. :)

**Comment by pawel-piatkowski-meelogic** [comment]
@pradel one more thing I noticed is that src/main/AndroidManifest.xml declares `android.permission.READ_SMS` which seems like it shouldn't be needed.
